"""Markdown plan exporter."""
from __future__ import annotations

from datetime import date, datetime, timezone

import pandas as pd


def export_plan_markdown(
    plan_df: pd.DataFrame,
    target_date: date,
    project_key: str,
    day_note: str = "",
    issue_notes: dict[str, str] | None = None,
    top_n: int = 15,
) -> str:
    """Generate a Markdown daily plan suitable for pasting into Slack/Notion."""
    if issue_notes is None:
        issue_notes = {}

    now_utc = datetime.now(timezone.utc).strftime("%H:%M UTC")
    date_str = target_date.strftime("%A, %B %d, %Y")

    lines: list[str] = [
        f"# ADAPT Engineering Daily Plan — {date_str}",
        f"**Project:** {project_key} · **Exported at:** {now_utc}",
        "",
        "---",
        "",
    ]

    # TL notes
    if day_note and day_note.strip():
        lines += ["## TL Notes", "", day_note.strip(), "", "---", ""]

    # Top N ranked items
    df = plan_df.head(top_n)
    if not df.empty:
        lines += ["## Priority Queue (Today's Focus)", ""]
        lines += ["| # | Issue | Summary | Assignee | Score | Override |"]
        lines += ["|---|-------|---------|----------|-------|----------|"]
        for _, row in df.iterrows():
            rank = row["plan_rank"]
            key = str(row.get("key", ""))
            summary = str(row.get("summary", ""))[:60]
            assignee = str(row.get("assignee") or "—")
            score = float(row.get("priority_score", 0))
            is_pinned = bool(row.get("is_pinned", False))
            reason = str(row.get("override_reason") or "")
            orig_rank = row.get("original_rank")

            rank_cell = f"📌" if is_pinned else str(rank)
            override_cell = ""
            if is_pinned:
                override_cell = f"📌 TL pinned" + (f": _{reason}_" if reason else "")
            elif pd.notna(row.get("rank_override")):
                override_cell = f"🔀 moved to #{rank}" + (f": _{reason}_" if reason else "")
            if orig_rank and not is_pinned and pd.isna(row.get("rank_override")):
                override_cell = ""  # pure algo rank, no note

            # Issue note
            if key in issue_notes:
                override_cell += f" 🗒 _{issue_notes[key]}_"

            lines.append(f"| {rank_cell} | **{key}** | {summary} | {assignee} | {score:.0f} | {override_cell} |")

        lines += ["", "---", ""]

    # Per-engineer breakdown
    if not df.empty and "assignee" in df.columns:
        lines += ["## By Engineer", ""]
        for engineer, grp in df.groupby("assignee", sort=False):
            lines += [f"### {engineer}", ""]
            for _, row in grp.iterrows():
                key = str(row.get("key", ""))
                summary = str(row.get("summary", ""))
                score = float(row.get("priority_score", 0))
                is_pinned = bool(row.get("is_pinned", False))
                reason = str(row.get("override_reason") or "")
                note = issue_notes.get(key, "")

                prefix = "📌" if is_pinned else f"{int(row['plan_rank'])}."
                pin_note = f" _(TL: {reason})_" if is_pinned and reason else ""
                issue_note_part = f"\n   > 🗒 {note}" if note else ""
                lines.append(f"{prefix} **{key}** — {summary} _(Score: {score:.0f})_{pin_note}{issue_note_part}")
            lines += [""]

        lines += ["---", ""]

    # Blockers section
    blocked_rows = plan_df[plan_df.get("is_blocked", pd.Series(dtype=bool)).astype(bool)] if "is_blocked" in plan_df.columns else pd.DataFrame()
    if not blocked_rows.empty:
        lines += ["## Blockers ⚠️", ""]
        for _, row in blocked_rows.iterrows():
            key = str(row.get("key", ""))
            summary = str(row.get("summary", ""))[:50]
            blockers_raw = str(row.get("blocker_keys") or "")
            blockers = [b.strip() for b in blockers_raw.split("|") if b.strip()]
            blocker_str = ", ".join(blockers) if blockers else "unknown"
            lines.append(f"- **{key}** ({summary}) — blocked by {blocker_str}")
        lines += ["", "---", ""]

    lines += [
        "_Generated by ADAPT Engineering Cockpit · Deterministic score + TL overrides_",
    ]

    return "\n".join(lines)
